version: '3'

services:

    php:
        build:
            context: ./docker/php
        ports:
            - 9000:9000
        volumes:
            - ${WEB_DOCUMENT_ROOT}:/srv/www/api
            - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
        environment:
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    nginx:
        image: nginx:1.13.8
        ports:
            - 80:80
        volumes:
            - ${WEB_DOCUMENT_ROOT}:/srv/www/api
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php

    mariadb:
        image: mariadb
        ports:
            - 3306:3306
        volumes:
            - ${DDBB_STORAGE}:/var/lib/mysql
        depends_on:
            - php
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    phpmyadmin:
        depends_on:
          - mariadb
        image: phpmyadmin/phpmyadmin
        environment:
          PMA_HOST: mariadb
          PMA_PORT: 3306
          PMA_ARBITRARY: 1
        restart: always
        container_name: phpmyadmin
        links:
          - mariadb
        restart: always
        ports:
         - 8080:80
